# 
# Multi architecture docker image
# Copyright 2021 Jamiel Sharief
#
name: Build Images
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build Images
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 --tag jamielsharief/php:latest --push .